sonar.projectKey=ContactManagementProject-Frontend
sonar.projectName=ContactManagementProject-Frontend
sonar.host.url=http://localhost:9000
sonar.token=sqp_c59a79eae72f5d32b6eae72aa910fec956c27ee5
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/build/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info